/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/runtime';
export namespace Components {
  /**
   * A simple component that takes in a first and last name and renders "Hello, World! I'm {first} {last}"
   */
  interface MyComponent {
    booleanTest: boolean;
    complexTest?: ComplexType;
    /**
     * The first name
     * @since 1.0.0
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     * @see https://example.com/middle-name
     */
    middle: string;
    numberTest?: number;
    /**
     * show radio control for < 5 options
     */
    radioTest?: 'foo' | 'bar' | 'baz';
    /**
     * show select control for >= 5 options
     */
    selectTest?: '1' | '2' | '3' | '4' | '5';
    /**
     * @default 'hello'
     */
    stringTest?: string;
  }
  interface MySlotted {}
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLMyComponentElement;
}
declare global {
  interface HTMLMyComponentElementEventMap {
    evalEvent: void;
  }
  /**
   * A simple component that takes in a first and last name and renders "Hello, World! I'm {first} {last}"
   */
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    addEventListener<K extends keyof HTMLMyComponentElementEventMap>(
      type: K,
      listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
    removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(
      type: K,
      listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLMySlottedElement extends Components.MySlotted, HTMLStencilElement {}
  var HTMLMySlottedElement: {
    prototype: HTMLMySlottedElement;
    new (): HTMLMySlottedElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'my-slotted': HTMLMySlottedElement;
  }
}
declare namespace LocalJSX {
  type OneOf<K extends string, PropT, AttrT = PropT> =
    | ({ [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never })
    | ({ [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never })
    | ({ [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never });

  /**
   * A simple component that takes in a first and last name and renders "Hello, World! I'm {first} {last}"
   */
  interface MyComponent {
    booleanTest: boolean;
    complexTest?: ComplexType;
    /**
     * The first name
     * @since 1.0.0
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     * @see https://example.com/middle-name
     */
    middle: string;
    numberTest?: number;
    onEvalEvent?: (event: MyComponentCustomEvent<void>) => void;
    /**
     * show radio control for < 5 options
     */
    radioTest?: 'foo' | 'bar' | 'baz';
    /**
     * show select control for >= 5 options
     */
    selectTest?: '1' | '2' | '3' | '4' | '5';
    /**
     * @default 'hello'
     */
    stringTest?: string;
  }
  interface MySlotted {}

  interface MyComponentAttributes {
    first: string;
    middle: string;
    last: string;
    radioTest: 'foo' | 'bar' | 'baz';
    selectTest: '1' | '2' | '3' | '4' | '5';
    booleanTest: boolean;
    numberTest: number;
    stringTest: string;
    complexTest: ComplexType;
  }

  interface IntrinsicElements {
    'my-component': Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & {
      [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K];
    } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] } & OneOf<'first', MyComponent['first'], MyComponentAttributes['first']> &
      OneOf<'middle', MyComponent['middle'], MyComponentAttributes['middle']> &
      OneOf<'last', MyComponent['last'], MyComponentAttributes['last']> &
      OneOf<'booleanTest', MyComponent['booleanTest'], MyComponentAttributes['booleanTest']>;
    'my-slotted': MySlotted;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * A simple component that takes in a first and last name and renders "Hello, World! I'm {first} {last}"
       */
      'my-component': LocalJSX.IntrinsicElements['my-component'] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'my-slotted': LocalJSX.IntrinsicElements['my-slotted'] & JSXBase.HTMLAttributes<HTMLMySlottedElement>;
    }
  }
}
