/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        "booleanTest": boolean;
        "complexTest"?: ComplexType;
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
        "numberTest"?: number;
        /**
          * show radio control for < 5 options
         */
        "radioTest"?: 'foo' | 'bar' | 'baz';
        /**
          * show select control for >= 5 options
         */
        "selectTest"?: '1' | '2' | '3' | '4' | '5';
        /**
          * @default 'hello'
         */
        "stringTest"?: string;
    }
    interface MySlotted {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMySlottedElement extends Components.MySlotted, HTMLStencilElement {
    }
    var HTMLMySlottedElement: {
        prototype: HTMLMySlottedElement;
        new (): HTMLMySlottedElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-slotted": HTMLMySlottedElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        "booleanTest"?: boolean;
        "complexTest"?: ComplexType;
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "numberTest"?: number;
        /**
          * show radio control for < 5 options
         */
        "radioTest"?: 'foo' | 'bar' | 'baz';
        /**
          * show select control for >= 5 options
         */
        "selectTest"?: '1' | '2' | '3' | '4' | '5';
        /**
          * @default 'hello'
         */
        "stringTest"?: string;
    }
    interface MySlotted {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-slotted": MySlotted;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-slotted": LocalJSX.MySlotted & JSXBase.HTMLAttributes<HTMLMySlottedElement>;
        }
    }
}
