packages:
  - packages/*
  
onlyBuiltDependencies:
  - edgedriver
  - esbuild
  - geckodriver

catalog:
  "@stencil/core": "^5.0.0 || >=5.0.0-alpha.19 <5.0.0-next.0"
  "@stencil/cli": "^5.0.0 || >=5.0.0-alpha.19 <5.0.0-next.0"